﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace WebApplication1
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"sepal_length", @"sepal_length"),new InputOutputColumnPair(@"sepal_width", @"sepal_width"),new InputOutputColumnPair(@"petal_length", @"petal_length"),new InputOutputColumnPair(@"petal_width", @"petal_width")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"sepal_length",@"sepal_width",@"petal_length",@"petal_width"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"iris_class", @"iris_class"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastForest(new FastForestBinaryTrainer.Options(){NumberOfTrees=6,FeatureFraction=1F,LabelColumnName=@"iris_class",FeatureColumnName=@"Features"}), labelColumnName: @"iris_class"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
