
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace IrisFlowerML
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLIrisFlower.ModelInput sampleData = new MLIrisFlower.ModelInput()
            {
                Sepal_length = 5.1F,
                Sepal_width = 3.5F,
                Petal_length = 1.4F,
                Petal_width = 0.2F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLIrisFlower.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Iris_class with predicted Iris_class from sample data...\n\n");


            Console.WriteLine($"Sepal_length: {5.1F}");
            Console.WriteLine($"Sepal_width: {3.5F}");
            Console.WriteLine($"Petal_length: {1.4F}");
            Console.WriteLine($"Petal_width: {0.2F}");
            Console.WriteLine($"Iris_class: {@"Iris-setosa"}");


            Console.WriteLine($"\n\nPredicted Iris_class: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
